#!/bin/bash

log () {
  [ -z "$quiet" ] && echo "$1"
}

banner () {
  log "___  _ ____ ____ ____ ____ _  _ ____"
  log "|  \ | |__/ [__  |    |  | |  | |__/"
  log "|__/ | |  \ ___] |___ |__| |__| |  \\"
  log ""
  log "Concocted by zbo14 with 🖤"
  log ""
}

usage () {
  echo "USAGE: ./dirscour [OPTIONS] <domain/@file>"
  echo ""
  echo "OPTIONS:"
  echo "  -h  log usage information and exit"
  echo "  -c  run in Docker container"
  echo "  -d  path to dirsearch directory"
  echo "  -o  path to output directory"
  echo "  -p  number of daemon processes to spawn (default: 20)"
  echo "  -q  don\'t print banner or info"
  echo "  -w  wordlist for web path discovery (default: <dirsearch>/db/dicc.txt)"
  exit
}

scanner () {
  id="$1"

  if [ "$1" -lt 10 ]; then
    id=0"$id"
  fi

  while true; do
    while true; do
      mkdir "$lock" 2> /dev/null && break
      sleep 1."$RANDOM"
    done

    subdomain="$(head -1 "$subdomains")"
    newsubdomains="$(tail -n +2 "$subdomains")"
    log "$newsubdomains" > "$subdomains"

    rm -rf "$lock"

    if [ "$subdomain" == "done" ]; then
      exit
    elif ! [[ "$subdomain" =~ [0-9A-Za-z]+ ]]; then
      sleep 1."$RANDOM"
      continue
    fi

    dns="$(dig +short "$subdomain")"

    if [[ "$dns" =~ [0-9A-Za-z]+ ]]; then
     log "[p#$id] Scanning \"$subdomain\""

      python3 "$dirsearch"/dirsearch.py \
        -E \
        -u https://"$subdomain" \
        --plain-text-report="$reports/$subdomain".txt \
        -w "$wordlist" \
        > /dev/null

      log "[p#$id] Finished \"$subdomain\""
    fi
  done
}

while getopts ":cd:ho:p:qw:" opt; do
  case ${opt} in
    h)
      usage
      ;;

    c)
      containerize=1
      ;;

    d)
      dirsearch="$(realpath "$OPTARG")"

      if [ ! -d "$dirsearch" ]; then
        echo "Couldn't find dirsearch directory \"$dirsearch\""
        exit 1
      elif [ ! -f "$dirsearch"/dirsearch.py ]; then
        echo "No dirsearch.py file in directory"
        exit 1
      fi
      ;;

    o)
      output="$(realpath "$OPTARG")"

      if [ ! -d "$output" ]; then
        echo "Couldn't find output directory \"$output\""
        exit 1
      fi
      ;;

    p)
      nprocs="$OPTARG"

      if ! [[ "$nprocs" =~ ^[0-9]+$ ]]; then
        echo "Expected -p to be an integer"
        exit 1
      elif [ "$nprocs" -lt 1 ]; then
        echo "Expected -p to be greater than/equal to 1"
        exit 1
      fi
      ;;

    q)
      quiet=1
      ;;

    w)
      wordlist="$(realpath "$OPTARG")"

      if [ ! -f "$wordlist" ]; then
        echo "Couldn't find wordlist \"$wordlist\""
        exit 1
      fi
      ;;

  esac
done

shift $((OPTIND-1))

if [ -z "$1" ]; then
  echo "No target domains specified"
  exit 1
elif [[ "$1" == @* ]]; then
  filename="$(realpath "$(echo "$1" | cut -c 2-)")"

  if [ ! -f "$filename" ]; then
    echo "Couldn't find file \"$filename\""
    exit 1
  fi
fi

nprocs=${nprocs:-20}
output=${output:-"$PWD"}
reports="$output"/reports

mkdir -p "$reports"

if [ ! -z "$containerize" ]; then
  if [ -z "$filename" ]; then
    if [ -z "$wordlist" ]; then
      docker run \
        -e nprocs="$nprocs" \
        -e target="$1" \
        -e wordlist=/dirscour/dirsearch/db/dicc.txt \
        --rm \
        -v "$output":/dirscour/output \
        dirscour
    else
      docker run \
        -e nprocs="$nprocs" \
        -e target="$1" \
        -e wordlist=/dirscour/wordlist \
        --rm \
        -v "$output":/dirscour/output \
        -v "$wordlist":/dirscour/wordlist:ro \
        dirscour
    fi
  elif  [ -z "$wordlist" ]; then
    docker run \
      -e nprocs="$nprocs" \
      -e target=@/dirscour/domains \
      -e wordlist=/dirscour/dirsearch/db/dicc.txt \
      --rm \
      -v "$filename":/dirscour/domains \
      -v "$output":/dirscour/output \
      dirscour
  else
    docker run \
      -e nprocs="$nprocs" \
      -e target=@/dirscour/domains \
      -e wordlist=/dirscour/wordlist \
      --rm \
      -v "$filename":/dirscour/domains \
      -v "$output":/dirscour/output \
      -v "$wordlist":/dirscour/wordlist:ro \
      dirscour
  fi

  exit "$?"
elif [ -z "$dirsearch" ]; then
  echo "No dirsearch directory specified"
  exit 1
fi

tmp="$(mktemp -d)"
lock="$tmp"/lock
subdomains="$tmp"/subdomains
wordlist=${wordlist:-"$dirsearch"/db/dicc.txt}

touch "$subdomains"

banner

log "[main] Starting scanner processes"

for i in $(seq 1 "$nprocs"); do
  scanner "$i" &
done

if [ -z "$filename" ]; then
  log "[main] Starting subdomain discovery of \"$1\""
  amass enum -passive -d "$1" >> "$subdomains" 2> /dev/null
  log "[main] Finished subdomain discovery"
else
  log "[main] Scanning domains in file"
  cp "$filename" "$subdomains"
fi

for _ in $(seq 1 "$nprocs"); do
  echo "done" >> "$subdomains"
done

wait

log "[main] Cleaning up"

rm -rf "$tmp"

log "[main] Done!"
